apiVersion: 1

policies:
  - orgId: 1
    receiver: Email Notifications
    group_by: ["alertname", "grafana_folder", "job"]
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 5m
    routes:
      - receiver: Email Notifications
        matchers:
          - alertname =~ ".*"
        continue: false
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 5m
